Repository blockscout/frontend, pull requests merged in 2024-12, with the labels that each got.

#2449 Zilliqa: filter for Scilla contracts
  configs/app/ui/views/address.ts
  configs/envs/.env.zilliqa_prototestnet
  deploy/tools/envs-validator/schema.ts
  deploy/tools/envs-validator/test/.env.base
  docs/ENVS.md
  types/api/contracts.ts
  types/client/contract.ts
  ui/verifiedContracts/VerifiedContractsFilter.tsx
Labels: ENVs

#2446 ReCaptcha: migrate back to v2 solution
  .env.example
  configs/app/features/account.ts
  configs/app/features/csvExport.ts
  configs/app/features/publicTagsSubmission.ts
  configs/app/services.ts
  configs/envs/.env.jest
  configs/envs/.env.pw
  deploy/tools/envs-validator/index.ts
  deploy/tools/envs-validator/schema.ts
  deploy/tools/envs-validator/test/.env.alt
  deploy/tools/envs-validator/test/.env.base
  deploy/values/review-l2/values.yaml.gotmpl
  deploy/values/review/values.yaml.gotmpl
  docs/DEPRECATED_ENVS.md
  docs/ENVS.md
  nextjs/csp/policies/googleReCaptcha.ts
  package.json
  playwright-ct.config.ts
  playwright/mocks/ui/shared/recaptcha/useReCaptcha.js
  theme/globals/recaptcha.ts
  ui/csvExport/CsvExportForm.tsx
  ui/csvExport/types.ts
  ui/myProfile/MyProfileEmail.tsx
  ui/myProfile/types.tsx
  ui/pages/TokenInstance.pw.tsx
  ui/pages/__screenshots__/TokenInstance.pw.tsx_default_metadata-update-failed-1.png
  ui/publicTags/submit/PublicTagsSubmitForm.tsx
  ui/publicTags/submit/types.ts
  ui/publicTags/submit/utils.test.ts
  ui/shared/AppError/custom/AppErrorTooManyRequests.tsx
  ui/shared/forms/fields/FormFieldReCaptcha.tsx
  ui/shared/layout/__screenshots__/Layout.pw.tsx_default_base-view-mobile-1.png
  ui/shared/layout/__screenshots__/Layout.pw.tsx_default_xxl-screen-horizontal-navigation-1.png
  ui/shared/layout/__screenshots__/Layout.pw.tsx_default_xxl-screen-vertical-navigation-1.png
  ui/shared/layout/__screenshots__/Layout.pw.tsx_mobile_base-view-mobile-1.png
  ui/shared/layout/__screenshots__/LayoutError.pw.tsx_default_base-view-mobile-1.png
  ui/shared/layout/__screenshots__/LayoutError.pw.tsx_mobile_base-view-mobile-1.png
  ui/shared/layout/__screenshots__/LayoutHome.pw.tsx_default_base-view-mobile-1.png
  ui/shared/layout/__screenshots__/LayoutHome.pw.tsx_mobile_base-view-mobile-1.png
  ui/shared/reCaptcha/ReCaptcha.tsx
  ui/shared/reCaptcha/useReCaptcha.tsx
  ui/snippets/auth/AuthModal.tsx
  ui/snippets/auth/screens/AuthModalScreenEmail.tsx
  ui/snippets/auth/screens/AuthModalScreenOtpCode.tsx
  ui/snippets/footer/Footer.tsx
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_dark-color-mode_with-custom-links-max-cols-mobile-dark-mode-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_dark-color-mode_with-custom-links-min-cols-base-view-dark-mode-mobile-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_dark-color-mode_without-custom-links-base-view-dark-mode-mobile-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_dark-color-mode_without-custom-links-with-indexing-alert-dark-mode-mobile-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_default_with-custom-links-max-cols-mobile-dark-mode-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_default_with-custom-links-max-cols-screen-xl-base-view-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_default_with-custom-links-min-cols-base-view-dark-mode-mobile-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_default_without-custom-links-base-view-dark-mode-mobile-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_default_without-custom-links-with-indexing-alert-dark-mode-mobile-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_mobile_with-custom-links-max-cols-mobile-dark-mode-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_mobile_with-custom-links-min-cols-base-view-dark-mode-mobile-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_mobile_without-custom-links-base-view-dark-mode-mobile-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_mobile_without-custom-links-with-indexing-alert-dark-mode-mobile-1.png
  ui/tokenInstance/TokenInstanceMetadataFetcher.tsx
  yarn.lock
Labels: dependencies, ENVs

#2344 SEO Tweaks for Gas Tracker Page
  lib/metadata/generate.ts
  lib/metadata/templates/description.ts
  lib/metadata/templates/title.ts
  ui/gasTracker/GasTrackerFaq.tsx
  ui/gasTracker/GasTrackerFaqItem.tsx
  ui/pages/GasTracker.pw.tsx
  ui/pages/GasTracker.tsx
  ui/pages/__screenshots__/GasTracker.pw.tsx_dark-color-mode_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/GasTracker.pw.tsx_default_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/GasTracker.pw.tsx_mobile_base-view-dark-mode-mobile-1.png
Labels: enhancement

#2451 Replace system selectors with Blockscout selectors style
  public/static/identicon_logos/nouns.svg
  ui/address/contract/ContractDetails.tsx
  ui/address/contract/ContractSourceAddressSelector.tsx
  ui/address/contract/__screenshots__/ContractDetails.pw.tsx_dark-color-mode_full-view-source-code-dark-mode-1.png
  ui/address/contract/__screenshots__/ContractDetails.pw.tsx_default_full-view-abi-1.png
  ui/address/contract/__screenshots__/ContractDetails.pw.tsx_default_full-view-bytecode-1.png
  ui/address/contract/__screenshots__/ContractDetails.pw.tsx_default_full-view-compiler-1.png
  ui/address/contract/__screenshots__/ContractDetails.pw.tsx_default_full-view-source-code-dark-mode-1.png
  ui/address/contract/__screenshots__/ContractDetails.pw.tsx_default_mobile-view-source-code-1.png
  ui/address/contract/__screenshots__/ContractDetails.pw.tsx_default_non-verified-1.png
  ui/address/contract/methods/__screenshots__/ContractMethodsProxy.pw.tsx_default_with-multiple-implementations-mobile-1.png
  ui/address/contract/methods/__screenshots__/ContractMethodsProxy.pw.tsx_mobile_with-multiple-implementations-mobile-1.png
  ui/blob/BlobData.pw.tsx
  ui/blob/BlobData.tsx
  ui/blob/__screenshots__/BlobData.pw.tsx_default_image-1.png
  ui/blob/__screenshots__/BlobData.pw.tsx_default_image-2.png
  ui/blob/__screenshots__/BlobData.pw.tsx_default_image-blob-with-zeroes-bytes-1.png
  ui/blob/__screenshots__/BlobData.pw.tsx_default_text-2.png
  ui/marketplace/utils.ts
  ui/nameDomains/utils.ts
  ui/pages/Chart.tsx
  ui/pages/__screenshots__/Chart.pw.tsx_dark-color-mode_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/Chart.pw.tsx_default_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/Chart.pw.tsx_mobile_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/TokenInstance.pw.tsx_default_metadata-update-1.png
  ui/pages/__screenshots__/TokenInstance.pw.tsx_default_metadata-update-3.png
  ui/pages/__screenshots__/TokenInstance.pw.tsx_default_metadata-update-failed-1.png
  ui/pages/__screenshots__/UserOp.pw.tsx_default_base-view-1.png
  ui/pages/__screenshots__/UserOp.pw.tsx_default_mobile-base-view-1.png
  ui/shared/RawInputData.tsx
  ui/shared/chart/ChartIntervalSelect.tsx
  ui/shared/chart/ChartResolutionSelect.tsx
  ui/shared/filters/PopoverFilterRadio.tsx
  ui/shared/logs/__screenshots__/LogItem.pw.tsx_default_with-default-data-type-1.png
  ui/shared/select/Select.tsx
  ui/shared/select/SelectButton.tsx
  ui/shared/select/SelectContent.tsx
  ui/shared/select/SelectOption.tsx
  ui/shared/select/types.ts
  ui/shared/sort/Sort.tsx
  ui/shared/sort/getSortValueFromQuery.ts
  ui/stats/StatsDropdownMenu.tsx
  ui/stats/StatsFilters.tsx
  ui/tokenInstance/TokenInstanceMetadata.pw.tsx
  ui/tokenInstance/TokenInstanceMetadata.tsx
  ui/tokenInstance/__screenshots__/TokenInstanceMetadata.pw.tsx_default_base-view-mobile-1.png
  ui/tokenInstance/__screenshots__/TokenInstanceMetadata.pw.tsx_default_raw-view-1.png
  ui/tokenInstance/__screenshots__/TokenInstanceMetadata.pw.tsx_mobile_base-view-mobile-1.png
  ui/tokens/utils.ts
  ui/tx/details/__screenshots__/TxInfo.pw.tsx_dark-color-mode_between-addresses-mobile-dark-mode-1.png
  ui/tx/details/__screenshots__/TxInfo.pw.tsx_default_between-addresses-mobile-dark-mode-1.png
  ui/tx/details/__screenshots__/TxInfo.pw.tsx_default_pending-1.png
  ui/tx/details/__screenshots__/TxInfo.pw.tsx_default_with-blob-1.png
  ui/tx/details/__screenshots__/TxInfo.pw.tsx_mobile_between-addresses-mobile-dark-mode-1.png
  ui/txs/useTxsSort.tsx
  ui/validatorsBlackfort/utils.ts
  ui/validatorsStability/utils.ts
  ui/verifiedContracts/utils.ts
Labels: design

#2456 Update Merits dashboard
  configs/envs/.env.eth_sepolia
  mocks/rewards/dailyReward.ts
  public/static/badges.svg
  public/static/badges/badge_1.svg
  public/static/badges/badge_2.svg
  public/static/badges/badge_3.svg
  public/static/badges/badge_4.svg
  public/static/badges/badge_5.svg
  types/api/rewards.ts
  ui/pages/RewardsDashboard.tsx
  ui/pages/__screenshots__/RewardsDashboard.pw.tsx_dark-color-mode_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/RewardsDashboard.pw.tsx_default_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/RewardsDashboard.pw.tsx_default_with-error-1.png
  ui/pages/__screenshots__/RewardsDashboard.pw.tsx_mobile_base-view-dark-mode-mobile-1.png
  ui/rewards/dashboard/DailyRewardClaimButton.tsx
  ui/rewards/dashboard/RewardsDashboardCard.tsx
  ui/rewards/login/steps/LoginStepContent.tsx
Labels: enhancement

#2338 Games
  configs/app/features/easterEggBadge.ts
  configs/app/features/index.ts
  configs/envs/.env.eth
  deploy/tools/envs-validator/schema.ts
  docs/ENVS.md
  nextjs/csp/policies/app.ts
  public/static/capibara/capybaraSprite.png
  public/static/capibara/capybaraSpriteX2.png
  public/static/capibara/index.js
  ui/games/CapybaraRunner.tsx
  ui/pages/BlockCountdown.pw.tsx
  ui/pages/BlockCountdown.tsx
  ui/pages/__screenshots__/BlockCountdown.pw.tsx_default_long-period-until-the-block-mobile-1.png
  ui/pages/__screenshots__/BlockCountdown.pw.tsx_default_short-period-until-the-block-mobile-1.png
Labels: enhancement, ENVs

#2478 Stats & charts: horizontal axis improvements
  ui/address/__screenshots__/AddressCoinBalance.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/address/__screenshots__/AddressCoinBalance.pw.tsx_default_base-view-dark-mode-1.png
  ui/address/__screenshots__/AddressCoinBalance.pw.tsx_default_mobile-base-view-1.png
  ui/address/__screenshots__/AddressCoinBalance.pw.tsx_mobile_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/Chart.pw.tsx_dark-color-mode_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/Chart.pw.tsx_default_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/Chart.pw.tsx_mobile_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/GasTracker.pw.tsx_dark-color-mode_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/GasTracker.pw.tsx_default_base-view-dark-mode-mobile-1.png
  ui/pages/__screenshots__/GasTracker.pw.tsx_mobile_base-view-dark-mode-mobile-1.png
  ui/shared/chart/ChartWidgetGraph.tsx
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_dark-color-mode_base-view-dark-mode-2.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_dark-color-mode_base-view-dark-mode-3.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_dark-color-mode_base-view-dark-mode-4.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_default_base-view-dark-mode-1.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_default_base-view-dark-mode-2.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_default_base-view-dark-mode-3.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_default_base-view-dark-mode-4.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_default_error-1.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_default_incomplete-day-1.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_default_incomplete-day-2.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_default_loading-1.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_default_small-values-1.png
  ui/shared/chart/__screenshots__/ChartWidget.pw.tsx_default_small-variations-in-big-values-1.png
  ui/shared/chart/utils/timeChartAxis.ts
Labels: enhancement
