Repository blockscout/frontend, pull requests merged in 2024-08, with the labels that each got.

#2142 Fix loading state of homepage on mobile
  .github/workflows/deploy-review-l2.yml
  configs/envs/.env.base
  ui/pages/Home.tsx
  ui/shared/ad/AdbutlerBanner.tsx
  ui/shared/ad/CoinzillaBanner.tsx
  ui/shared/layout/components/Container.tsx
Labels: bug

#2138 Fix marketplace sorting display
  ui/marketplace/utils.ts
  ui/pages/Marketplace.tsx
Labels: bug

#2133 Fix "connect wallet" button tooltip
  ui/snippets/walletMenu/WalletMenuDesktop.tsx
Labels: bug

#2132 Fix marketplace search query
  ui/marketplace/useMarketplace.tsx
  ui/marketplace/useMarketplaceApps.tsx
  ui/shared/EmptySearchResult.tsx
Labels: bug

#2157 UML diagram caching
  lib/api/useApiQuery.tsx
  ui/sol2uml/Sol2UmlDiagram.tsx
Labels: bug

#2156 ENS: add offchain support and fix bugs
  mocks/ens/domain.ts
  package.json
  stubs/ENS.ts
  ui/address/ensDomains/AddressEnsDomains.tsx
  ui/nameDomain/NameDomainDetails.tsx
  ui/nameDomain/details/NameDomainDetailsAlert.tsx
  ui/pages/Address.tsx
  ui/pages/__screenshots__/NameDomain.pw.tsx_default_details-tab-1.png
  ui/pages/__screenshots__/NameDomain.pw.tsx_default_history-tab-mobile-1.png
  ui/pages/__screenshots__/NameDomain.pw.tsx_mobile_history-tab-mobile-1.png
  yarn.lock
Labels: enhancement

#2115 Pack Chakra theme into NPM package
  .github/workflows/chakra-npm-publisher.yml
  configs/app/utils.ts
  jest/lib.tsx
  lib/contexts/chakra.tsx
  pages/_document.tsx
  playwright/TestApp.tsx
  theme/.gitignore
  theme/package-lock.json
  theme/package.json
  theme/theme.ts
  theme/tsconfig.json
  theme/webpack.config.js
  theme/yarn.lock
  ui/shared/FancySelect/utils.ts
Labels: tech

#2160 check redirect only on search bar submit
  ui/pages/SearchResults.tsx
  ui/snippets/searchBar/SearchBar.tsx
  ui/snippets/searchBar/useSearchQuery.tsx
Labels: bug

#2154 mud design fixes
  ui/address/mud/AddressMudRecordsTable.tsx
  ui/address/mud/AddressMudTablesTableItem.tsx
  ui/address/mud/__screenshots__/AddressMudTable.pw.tsx_default_base-view-mobile-1.png
  ui/address/mud/__screenshots__/AddressMudTable.pw.tsx_default_expanded-view-mobile-1.png
  ui/address/mud/__screenshots__/AddressMudTable.pw.tsx_mobile_base-view-mobile-1.png
  ui/address/mud/__screenshots__/AddressMudTable.pw.tsx_mobile_expanded-view-mobile-1.png
  ui/address/mud/__screenshots__/AddressMudTables.pw.tsx_default_base-view-mobile-1.png
Labels: bug

#2164 Cancel previous search queries when typing
  lib/api/useApiQuery.tsx
Labels: performance

#2153 Display ENS on the wallet button and in the menu
  configs/envs/.env.pw
  lib/api/resources.ts
  ui/snippets/header/__screenshots__/Burger.pw.tsx_default_submenu-1.png
  ui/snippets/navigation/vertical/__screenshots__/NavigationDesktop.pw.tsx_default_with-highlighted-routes-with-submenu-1.png
  ui/snippets/navigation/vertical/__screenshots__/NavigationDesktop.pw.tsx_default_with-submenu-1.png
  ui/snippets/navigation/vertical/__screenshots__/NavigationDesktop.pw.tsx_default_with-submenu-xl-screen-1.png
  ui/snippets/walletMenu/WalletMenuContent.tsx
  ui/snippets/walletMenu/WalletMenuDesktop.pw.tsx
  ui/snippets/walletMenu/WalletMenuDesktop.tsx
  ui/snippets/walletMenu/WalletMenuMobile.pw.tsx
  ui/snippets/walletMenu/WalletMenuMobile.tsx
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_dark-color-mode_wallet-connected-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_dark-color-mode_wallet-connected-home-page-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_dark-color-mode_wallet-is-not-connected-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_dark-color-mode_wallet-is-not-connected-home-page-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_default_wallet-connected-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_default_wallet-connected-home-page-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_default_wallet-is-loading-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_default_wallet-is-not-connected-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_default_wallet-is-not-connected-home-page-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_default_wallet-with-ENS-connected-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuMobile.pw.tsx_dark-color-mode_wallet-connected-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuMobile.pw.tsx_dark-color-mode_wallet-is-not-connected-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuMobile.pw.tsx_default_wallet-connected-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuMobile.pw.tsx_default_wallet-is-loading-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuMobile.pw.tsx_default_wallet-is-not-connected-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuMobile.pw.tsx_default_wallet-with-ENS-connected-1.png
Labels: enhancement

#2191 Metadata: show Notes
  lib/address/parseMetaPayload.ts
  mocks/metadata/address.ts
  theme/components/Alert/Alert.ts
  types/api/addressMetadata.ts
  ui/address/details/AddressMetadataAlert.pw.tsx
  ui/address/details/AddressMetadataAlert.tsx
  ui/address/details/__screenshots__/AddressMetadataAlert.pw.tsx_default_base-view-1.png
  ui/pages/Address.tsx
Labels: enhancement

#2197 Limit page content width
  deploy/values/review-l2/values.yaml.gotmpl
  pages/_app.tsx
  playwright/ContentWrapper.tsx
  playwright/fixtures/render.tsx
  theme/components/Tooltip/__screenshots__/Tooltip.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  theme/global.ts
  ui/address/__screenshots__/SolidityscanReport.pw.tsx_dark-color-mode_average-report-dark-mode-mobile-1.png
  ui/address/__screenshots__/SolidityscanReport.pw.tsx_dark-color-mode_average-report-dark-mode-mobile-2.png
  ui/address/tokenSelect/__screenshots__/TokenSelect.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/address/tokenSelect/__screenshots__/TokenSelect.pw.tsx_dark-color-mode_base-view-dark-mode-2.png
  ui/gasTracker/__screenshots__/GasTrackerPriceSnippet.pw.tsx_dark-color-mode_with-gwei-as-primary-unit-dark-mode-1.png
  ui/gasTracker/__screenshots__/GasTrackerPriceSnippet.pw.tsx_dark-color-mode_with-usd-as-primary-unit-dark-mode-1.png
  ui/marketplace/__screenshots__/MarketplaceAppInfo.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/pages/NameDomain.pw.tsx
  ui/pages/__screenshots__/NameDomain.pw.tsx_default_details-tab-1.png
  ui/pages/__screenshots__/NameDomain.pw.tsx_default_history-tab-mobile-1.png
  ui/pages/__screenshots__/NameDomain.pw.tsx_mobile_history-tab-mobile-1.png
  ui/shared/AppError/AppErrorBoundary.tsx
  ui/shared/AppError/AppErrorGlobalContainer.tsx
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_dark-color-mode_tag-with-tooltip-dark-mode-1.png
  ui/shared/FancySelect/__screenshots__/FancySelect.pw.tsx_dark-color-mode_size-lg-dark-mode-empty-2.png
  ui/shared/FancySelect/__screenshots__/FancySelect.pw.tsx_dark-color-mode_size-md-dark-mode-empty-2.png
  ui/shared/Tabs/AdaptiveTabsList.tsx
  ui/shared/Tabs/TabsWithScroll.tsx
  ui/shared/entities/address/AddressEntity.tsx
  ui/shared/layout/Layout.pw.tsx
  ui/shared/layout/__screenshots__/Layout.pw.tsx_default_xl-screen-horizontal-navigation-1.png
  ui/shared/layout/__screenshots__/Layout.pw.tsx_default_xl-screen-vertical-navigation-1.png
  ui/shared/layout/components/Container.tsx
  ui/shared/layout/components/MainArea.tsx
  ui/shared/layout/components/MainColumn.tsx
  ui/shared/layout/utils.ts
  ui/snippets/footer/Footer.tsx
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_dark-color-mode_with-custom-links-max-cols-mobile-dark-mode-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_dark-color-mode_with-custom-links-min-cols-base-view-dark-mode-mobile-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_dark-color-mode_without-custom-links-base-view-dark-mode-mobile-1.png
  ui/snippets/footer/__screenshots__/Footer.pw.tsx_default_with-custom-links-max-cols-screen-xl-1.png
  ui/snippets/header/__screenshots__/HeaderMobile.pw.tsx_dark-color-mode_default-view-dark-mode-1.png
  ui/snippets/navigation/horizontal/NavigationDesktop.tsx
  ui/snippets/navigation/horizontal/__screenshots__/NavigationDesktop.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/snippets/networkMenu/__screenshots__/NetworkMenu.pw.tsx_dark-color-mode_base-view-dark-mode-3.png
  ui/snippets/networkMenu/__screenshots__/NetworkMenu.pw.tsx_dark-color-mode_base-view-dark-mode-4.png
  ui/snippets/profileMenu/__screenshots__/ProfileMenuDesktop.pw.tsx_dark-color-mode_auth-dark-mode-1.png
  ui/snippets/topBar/TopBar.tsx
  ui/snippets/topBar/__screenshots__/TopBar.pw.tsx_dark-color-mode_default-view-dark-mode-mobile-1.png
  ui/snippets/topBar/__screenshots__/TopBar.pw.tsx_dark-color-mode_default-view-dark-mode-mobile-2.png
  ui/snippets/topBar/__screenshots__/TopBar.pw.tsx_dark-color-mode_with-DeFi-dropdown-dark-mode-mobile-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_dark-color-mode_wallet-connected-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_dark-color-mode_wallet-connected-home-page-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_dark-color-mode_wallet-is-not-connected-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuDesktop.pw.tsx_dark-color-mode_wallet-is-not-connected-home-page-dark-mode-1.png
  ui/snippets/walletMenu/__screenshots__/WalletMenuMobile.pw.tsx_dark-color-mode_wallet-is-not-connected-dark-mode-1.png
  ui/txs/__screenshots__/TxAdditionalInfo.pw.tsx_dark-color-mode_regular-transaction-dark-mode-1.png
Labels: bug

#2185 Celo: Block views customizations
  icons/checkered_flag.svg
  lib/api/resources.ts
  lib/api/useApiFetch.tsx
  lib/api/useApiInfiniteQuery.tsx
  lib/api/useApiQuery.tsx
  mocks/blocks/block.ts
  mocks/blocks/epoch.ts
  public/icons/name.d.ts
  stubs/block.ts
  stubs/token.ts
  theme/foundations/colors.ts
  types/api/block.ts
  types/api/stats.ts
  ui/block/BlockDetails.tsx
  ui/block/BlockEpochRewards.tsx
  ui/block/details/BlockDetailsBaseFeeCelo.pw.tsx
  ui/block/details/BlockDetailsBaseFeeCelo.tsx
  ui/block/details/__screenshots__/BlockDetailsBaseFeeCelo.pw.tsx_default_base-view-mobile-1.png
  ui/block/details/__screenshots__/BlockDetailsBaseFeeCelo.pw.tsx_mobile_base-view-mobile-1.png
  ui/block/epochRewards/BlockEpochElectionRewardDetailsDesktop.tsx
  ui/block/epochRewards/BlockEpochElectionRewardDetailsMobile.tsx
  ui/block/epochRewards/BlockEpochElectionRewardType.tsx
  ui/block/epochRewards/BlockEpochElectionRewards.pw.tsx
  ui/block/epochRewards/BlockEpochElectionRewards.tsx
  ui/block/epochRewards/BlockEpochElectionRewardsListItem.tsx
  ui/block/epochRewards/BlockEpochElectionRewardsTableItem.tsx
  ui/block/epochRewards/BlockEpochRewardsDistribution.tsx
  ui/block/epochRewards/__screenshots__/BlockEpochElectionRewards.pw.tsx_default_base-view-mobile-1.png
  ui/block/epochRewards/__screenshots__/BlockEpochElectionRewards.pw.tsx_mobile_base-view-mobile-1.png
  ui/block/epochRewards/utils.ts
  ui/blocks/BlocksListItem.tsx
  ui/blocks/BlocksTable.tsx
  ui/blocks/BlocksTableItem.tsx
  ui/home/LatestBlocks.tsx
  ui/home/LatestBlocksItem.tsx
  ui/home/Stats.tsx
  ui/pages/Block.tsx
  ui/pages/__screenshots__/Blocks.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/pages/__screenshots__/Blocks.pw.tsx_default_base-view-dark-mode-1.png
  ui/pages/__screenshots__/Blocks.pw.tsx_default_hidden-fields-1.png
  ui/pages/__screenshots__/Blocks.pw.tsx_default_new-item-from-socket-1.png
  ui/pages/__screenshots__/Blocks.pw.tsx_default_socket-error-1.png
  ui/shared/DetailsInfoItem.tsx
  ui/shared/HintPopover.tsx
  ui/shared/TokenTransferSnippet/TokenTransferSnippet.tsx
  ui/shared/TokenTransferSnippet/TokenTransferSnippetFiat.tsx
  ui/shared/TokenTransferSnippet/TokenTransferSnippetNft.tsx
  ui/shared/entities/address/AddressEntityContentProxy.tsx
  ui/shared/entities/base/components.tsx
  ui/shared/pagination/useLazyLoadedList.tsx
  ui/sol2uml/Sol2UmlDiagram.tsx
  ui/tx/details/TxDetailsTokenTransfers.tsx
Labels: enhancement

#2198 Add rating count
  icons/share.svg
  mocks/apps/ratings.ts
  public/icons/name.d.ts
  types/client/marketplace.ts
  ui/marketplace/FavoriteIcon.tsx
  ui/marketplace/MarketplaceAppCard.tsx
  ui/marketplace/MarketplaceAppModal.tsx
  ui/marketplace/MarketplaceAppTopBar.tsx
  ui/marketplace/MarketplaceList.tsx
  ui/marketplace/Rating/Rating.tsx
  ui/marketplace/Rating/TriggerButton.tsx
  ui/marketplace/Rating/useRatings.tsx
  ui/marketplace/__screenshots__/MarketplaceAppModal.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/marketplace/__screenshots__/MarketplaceAppModal.pw.tsx_default_base-view-dark-mode-1.png
  ui/marketplace/__screenshots__/MarketplaceAppModal.pw.tsx_default_mobile-base-view-1.png
  ui/pages/Marketplace.pw.tsx
  ui/pages/MarketplaceApp.pw.tsx
  ui/pages/__screenshots__/Marketplace.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_dark-color-mode_with-banner-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_dark-color-mode_with-featured-app-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_base-view-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-base-view-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-with-banner-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-with-featured-app-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_with-banner-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_with-featured-app-dark-mode-1.png
  ui/pages/__screenshots__/MarketplaceApp.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/pages/__screenshots__/MarketplaceApp.pw.tsx_default_base-view-dark-mode-1.png
  ui/pages/__screenshots__/MarketplaceApp.pw.tsx_default_mobile-base-view-1.png
  ui/shared/CopyToClipboard.tsx
Labels: enhancement
