Repository blockscout/frontend, pull requests merged in 2024-05, with the labels that each got.

#1851 Get smart-contract bytecode from websocket
  deploy/values/review/values.yaml.gotmpl
  lib/socket/types.ts
  mocks/address/tabCounters.ts
  playwright/fixtures/socketServer.ts
  ui/pages/Address.pw.tsx
  ui/pages/Address.tsx
Labels: QA

#1877 Public tags: display name tags for addresses
  deploy/values/review/values.yaml.gotmpl
  lib/address/parseMetaPayload.ts
  lib/makePrettyLink.ts
  lib/mixpanel/utils.ts
  mocks/address/address.ts
  mocks/metadata/address.ts
  types/api/addressMetadata.ts
  types/api/addressParams.ts
  types/client/addressMetadata.ts
  ui/pages/Address.tsx
  ui/pages/Token.tsx
  ui/pages/Transaction.tsx
  ui/pages/__screenshots__/Token.pw.tsx_default_bridged-token-1.png
  ui/shared/EntityTags.tsx
  ui/shared/EntityTags/EntityTag.pw.tsx
  ui/shared/EntityTags/EntityTag.tsx
  ui/shared/EntityTags/EntityTagLink.tsx
  ui/shared/EntityTags/EntityTagPopover.tsx
  ui/shared/EntityTags/EntityTags.tsx
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_dark-color-mode_custom-name-tag-dark-mode-1.png
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_dark-color-mode_generic-tag-dark-mode-1.png
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_dark-color-mode_protocol-tag-dark-mode-1.png
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_dark-color-mode_tag-with-link-and-long-name-dark-mode-1.png
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_dark-color-mode_tag-with-tooltip-dark-mode-1.png
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_default_custom-name-tag-dark-mode-1.png
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_default_generic-tag-dark-mode-1.png
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_default_protocol-tag-dark-mode-1.png
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_default_tag-with-link-and-long-name-dark-mode-1.png
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_default_tag-with-tooltip-dark-mode-1.png
  ui/shared/EntityTags/formatUserTags.ts
  ui/shared/EntityTags/sortEntityTags.ts
  ui/shared/EntityTags/types.ts
  ui/shared/LinkExternal.tsx
  ui/shared/Page/__screenshots__/PageTitle.pw.tsx_default_with-long-name-and-many-tags-mobile-1.png
  ui/shared/Page/__screenshots__/PageTitle.pw.tsx_mobile_with-long-name-and-many-tags-mobile-1.png
  ui/shared/Page/specs/DefaultView.tsx
  ui/shared/Page/specs/LongNameAndManyTags.tsx
  ui/shared/TruncatedTextTooltip.tsx
  ui/shared/TruncatedValue.tsx
  ui/shared/chakra/Tag.tsx
  ui/shared/entities/address/AddressEntity.pw.tsx
  ui/shared/entities/address/AddressEntity.tsx
  ui/shared/entities/address/__screenshots__/AddressEntity.pw.tsx_default_with-name-tag-1.png
  ui/token/TokenPageTitle.tsx
Labels: QA

#1882 Add ENV variable allowing to choose default color schema
  configs/app/ui.ts
  deploy/tools/envs-validator/schema.ts
  deploy/tools/envs-validator/test/.env.base
  deploy/values/review/values.yaml.gotmpl
  docs/ENVS.md
  lib/contexts/chakra.tsx
  lib/settings/colorTheme.ts
  lib/settings/identIcon.ts
  middleware.ts
  nextjs/middlewares/colorTheme.ts
  nextjs/middlewares/index.ts
  pages/_app.tsx
  theme/config.ts
  types/settings.ts
  ui/snippets/topBar/settings/SettingsColorTheme.tsx
  ui/snippets/topBar/settings/SettingsIdentIcon.tsx
Labels: QA

#1915 Release v1.30.0 fixes
  nextjs/csp/policies/app.ts
Labels: skip checks

#1922 Hotfix: content security policy and image size issues
  nextjs/csp/policies/app.ts
  ui/marketplace/MarketplaceListWithScores/AppLink.tsx
Labels: bug

#1930 Move generated assets into separate folder inside the public folder
  .gitignore
  Dockerfile
  configs/app/utils.ts
  deploy/scripts/entrypoint.sh
  deploy/scripts/favicon_generator.sh
  deploy/scripts/make_envs_script.sh
  deploy/tools/envs-validator/test.sh
  deploy/tools/envs-validator/test/assets/configs/featured_networks.json
  deploy/tools/envs-validator/test/assets/configs/footer_links.json
  deploy/tools/envs-validator/test/assets/configs/marketplace_categories.json
  deploy/tools/envs-validator/test/assets/configs/marketplace_config.json
  deploy/tools/envs-validator/test/assets/configs/marketplace_security_reports.json
  docs/ENVS.md
  instrumentation.node.ts
  next.config.js
  pages/_document.tsx
  public/README.md
  public/assets/favicon/apple-touch-icon-120x120.png
  public/assets/favicon/apple-touch-icon-152x152.png
  public/assets/favicon/apple-touch-icon-180x180.png
  public/assets/favicon/apple-touch-icon-60x60.png
  public/assets/favicon/apple-touch-icon-76x76.png
  public/assets/favicon/apple-touch-icon.png
  public/assets/favicon/favicon-16x16.png
  public/assets/favicon/favicon-32x32.png
  public/assets/favicon/favicon.ico
  public/assets/favicon/safari-pinned-tab.svg
  public/favicon/safari-pinned-tab.svg
  tools/scripts/dev.preset.sh
  tools/scripts/dev.sh
  tools/scripts/favicon-generator.dev.sh
Labels: tech

#1939 More custom elements for public tags
  lib/address/parseMetaPayload.ts
  mocks/metadata/address.ts
  types/api/addressMetadata.ts
  ui/shared/EntityTags/EntityTag.pw.tsx
  ui/shared/EntityTags/EntityTag.tsx
  ui/shared/EntityTags/EntityTagLink.tsx
  ui/shared/EntityTags/__screenshots__/EntityTag.pw.tsx_default_warpcast-tag-1.png
  ui/shared/EntityTags/utils.ts
Labels: enhancement

#1941 Gas tracker improvements
  ui/gasTracker/GasTrackerPriceSnippet.pw.tsx
  ui/gasTracker/__screenshots__/GasTrackerPriceSnippet.pw.tsx_default_with-small-values-1.png
  ui/home/Stats.pw.tsx
  ui/home/Stats.tsx
  ui/pages/GasTracker.tsx
  ui/shared/gas/formatGasValue.ts
  ui/txs/TxsStats.tsx
  ui/verifiedContracts/VerifiedContractsCounters.tsx
Labels: enhancement

#1945 Loader state for SolidityScan button
  configs/envs/.env.eth
  ui/address/SolidityscanReport.tsx
  ui/marketplace/AppSecurityReport.tsx
  ui/marketplace/MarketplaceListWithScores/ListItem.tsx
  ui/pages/Address.tsx
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-with-scores-1.png
  ui/shared/solidityscanReport/SolidityscanReportButton.tsx
Labels: enhancement

#1944 remove unsupported features from search results
  playwright/fixtures/mockEnvs.ts
  ui/pages/SearchResults.pw.tsx
  ui/pages/SearchResults.tsx
  ui/shared/search/utils.ts
  ui/snippets/searchBar/SearchBar.pw.tsx
Labels: bug

#1940 add certified conract label
  configs/envs/.env.eth_sepolia
  icons/certified.svg
  mocks/contract/info.ts
  mocks/contracts/index.ts
  mocks/search/index.ts
  public/icons/name.d.ts
  types/api/contract.ts
  types/api/contracts.ts
  types/api/search.ts
  ui/address/contract/ContractCode.pw.tsx
  ui/address/contract/ContractCode.tsx
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_default_with-certified-icon-mobile-1.png
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_mobile_with-certified-icon-mobile-1.png
  ui/pages/SearchResults.pw.tsx
  ui/pages/__screenshots__/SearchResults.pw.tsx_default_search-by-address-hash-mobile-1.png
  ui/pages/__screenshots__/SearchResults.pw.tsx_mobile_search-by-address-hash-mobile-1.png
  ui/pages/__screenshots__/VerifiedContracts.pw.tsx_default_base-view-mobile-1.png
  ui/pages/__screenshots__/VerifiedContracts.pw.tsx_mobile_base-view-mobile-1.png
  ui/searchResults/SearchResultListItem.tsx
  ui/searchResults/SearchResultTableItem.tsx
  ui/shared/ContractCertifiedLabel.tsx
  ui/shared/Page/specs/DefaultView.tsx
  ui/shared/Page/specs/LongNameAndManyTags.tsx
  ui/snippets/searchBar/SearchBar.pw.tsx
  ui/snippets/searchBar/SearchBarSuggest/SearchBarSuggestAddress.tsx
  ui/snippets/searchBar/SearchBarSuggest/SearchBarSuggestToken.tsx
  ui/snippets/searchBar/__screenshots__/SearchBar.pw.tsx_dark-color-mode_search-by-contract-name-mobile-dark-mode-1.png
  ui/snippets/searchBar/__screenshots__/SearchBar.pw.tsx_default_search-by-contract-name-mobile-dark-mode-1.png
  ui/snippets/searchBar/__screenshots__/SearchBar.pw.tsx_mobile_search-by-contract-name-mobile-dark-mode-1.png
  ui/token/TokenPageTitle.tsx
  ui/verifiedContracts/VerifiedContractsListItem.tsx
  ui/verifiedContracts/VerifiedContractsTableItem.tsx
Labels: client feature

#1951 Sidebar, latest txs and verified contracts improvements
  ui/home/LatestTxsItem.tsx
  ui/home/__screenshots__/LatestTxs.pw.tsx_dark-color-mode_default-view-dark-mode-1.png
  ui/home/__screenshots__/LatestTxs.pw.tsx_default_default-view-dark-mode-1.png
  ui/home/__screenshots__/LatestTxs.pw.tsx_default_socket-new-item-1.png
  ui/pages/__screenshots__/Home.pw.tsx_dark-color-mode_default-view---default-dark-mode-1.png
  ui/pages/__screenshots__/Home.pw.tsx_default_default-view-screen-xl-1.png
  ui/snippets/navigation/NavigationDesktop.tsx
  ui/verifiedContracts/VerifiedContractsTable.tsx
Labels: bug, chore

#1910 Menu lightning labels
  configs/app/ui.ts
  configs/envs/.env.eth_goerli
  configs/envs/.env.eth_sepolia
  configs/envs/.env.main
  deploy/tools/envs-validator/schema.ts
  deploy/tools/envs-validator/test/.env.base
  docs/ENVS.md
  icons/lightning_navbar.svg
  playwright/fixtures/mockEnvs.ts
  public/icons/name.d.ts
  ui/snippets/navigation/LightningLabel.tsx
  ui/snippets/navigation/NavLink.tsx
  ui/snippets/navigation/NavLinkGroupDesktop.tsx
  ui/snippets/navigation/NavLinkGroupMobile.tsx
  ui/snippets/navigation/NavigationDesktop.pw.tsx
  ui/snippets/navigation/__screenshots__/NavigationDesktop.pw.tsx_dark-color-mode_with-highlighted-routes-dark-mode-1.png
  ui/snippets/navigation/__screenshots__/NavigationDesktop.pw.tsx_dark-color-mode_with-highlighted-routes-xl-screen-dark-mode-1.png
  ui/snippets/navigation/__screenshots__/NavigationDesktop.pw.tsx_default_with-highlighted-routes-dark-mode-1.png
  ui/snippets/navigation/__screenshots__/NavigationDesktop.pw.tsx_default_with-highlighted-routes-with-submenu-1.png
  ui/snippets/navigation/__screenshots__/NavigationDesktop.pw.tsx_default_with-highlighted-routes-xl-screen-dark-mode-1.png
  ui/snippets/navigation/utils.ts
Labels: enhancement, ENVs

#1958 OP Fault Proofs support
  configs/app/features/faultProofSystem.ts
  configs/app/features/index.ts
  configs/envs/.env.optimism_sepolia
  deploy/tools/envs-validator/schema.ts
  deploy/tools/envs-validator/test/.env.rollup
  docs/ENVS.md
  icons/games.svg
  lib/api/resources.ts
  lib/hooks/useNavItems.tsx
  lib/metadata/getPageOgType.ts
  lib/metadata/templates/description.ts
  lib/metadata/templates/title.ts
  lib/mixpanel/getPageType.ts
  mocks/l2disputeGames/disputeGames.ts
  nextjs/getServerSideProps.ts
  nextjs/nextjs-routes.d.ts
  pages/dispute-games/index.tsx
  playwright/fixtures/mockEnvs.ts
  public/icons/name.d.ts
  stubs/L2.ts
  types/api/optimisticL2.ts
  ui/disputeGames/optimisticL2/OptimisticL2DisputeGamesListItem.tsx
  ui/disputeGames/optimisticL2/OptimisticL2DisputeGamesTable.tsx
  ui/disputeGames/optimisticL2/OptimisticL2DisputeGamesTableItem.tsx
  ui/pages/OptimisticL2DisputeGames.pw.tsx
  ui/pages/OptimisticL2DisputeGames.tsx
  ui/pages/__screenshots__/OptimisticL2DisputeGames.pw.tsx_default_base-view-mobile-1.png
  ui/pages/__screenshots__/OptimisticL2DisputeGames.pw.tsx_mobile_base-view-mobile-1.png
  ui/tx/details/TxDetailsWithdrawalStatus.tsx
Labels: feature, ENVs

#1963 Add support for Diamond proxy standard
  configs/envs/.env.eth
  mocks/address/address.ts
  mocks/blocks/block.ts
  mocks/contracts/index.ts
  mocks/l2withdrawals/withdrawals.ts
  mocks/shibarium/deposits.ts
  mocks/shibarium/withdrawals.ts
  mocks/tokens/tokenTransfer.ts
  mocks/txs/internalTxs.ts
  mocks/txs/state.ts
  mocks/txs/tx.ts
  mocks/txs/txInterpretation.ts
  mocks/userOps/userOp.ts
  mocks/userOps/userOps.ts
  mocks/withdrawals/withdrawals.ts
  stubs/address.ts
  stubs/addressParams.ts
  types/api/address.ts
  types/api/addressParams.ts
  ui/address/AddressDetails.tsx
  ui/address/contract/ContractCode.pw.tsx
  ui/address/contract/ContractCode.tsx
  ui/address/contract/ContractCodeIdes.tsx
  ui/address/contract/ContractExternalLibraries.tsx
  ui/address/contract/ContractImplementationAddress.tsx
  ui/address/contract/ContractSecurityAudits.tsx
  ui/address/contract/ContractSourceCode.tsx
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_default_verified-with-changed-byte-code-socket-1.png
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_default_verified-with-multiple-sources-1.png
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_default_verified-with-multiple-sources-2.png
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_default_verified-with-multiple-sources-3.png
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_default_with-audits-feature-has-audits-1.png
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_default_with-audits-feature-no-audits-1.png
  ui/address/details/AddressImplementations.tsx
  ui/address/details/AddressNetWorth.tsx
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_dark-color-mode_with-multichain-button-internal-dark-mode-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-external-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-internal-dark-mode-1.png
  ui/address/utils/useAddressQuery.ts
  ui/deposits/optimisticL2/OptimisticDepositsListItem.tsx
  ui/deposits/optimisticL2/OptimisticDepositsTableItem.tsx
  ui/pages/Address.tsx
  ui/pages/ContractVerificationForAddress.tsx
  ui/pages/Sol2Uml.tsx
  ui/pages/TokenInstance.tsx
  ui/searchResults/SearchResultListItem.tsx
  ui/searchResults/SearchResultTableItem.tsx
  ui/shared/ContainerWithScrollY.tsx
  ui/shared/DetailsActionsWrapper.tsx
  ui/shared/DetailsInfoItem.tsx
  ui/shared/address/utils.ts
  ui/shared/entities/address/AddressEntity.tsx
  ui/snippets/searchBar/SearchBarSuggest/SearchBarSuggestAddress.tsx
  ui/tokenInstance/details/TokenInstanceCreatorAddress.tsx
  ui/tokens/TokensTableItem.tsx
  ui/verifiedAddresses/VerifiedAddressesListItem.tsx
  ui/verifiedAddresses/VerifiedAddressesTableItem.tsx
Labels: feature

#1959 Token Instance Page: move critical requests to the page root
  pages/token/[hash]/instance/[id].tsx
  ui/pages/TokenInstance.tsx
  ui/tokenInstance/TokenInstanceDetails.tsx
Labels: performance
