Repository blockscout/frontend, pull requests merged in 2024-10, with the labels that each got.

#2289 Public tags: improvement batch
  mocks/metadata/address.ts
  ui/address/details/AddressMetadataAlert.pw.tsx
  ui/address/details/AddressMetadataAlert.tsx
  ui/address/details/__screenshots__/AddressMetadataAlert.pw.tsx_default_base-view-1.png
  ui/pages/Address.tsx
  ui/shared/EntityTags/EntityTags.tsx
Labels: bug

#2284 Graph integration
  configs/app/features/marketplace.ts
  configs/envs/.env.gnosis
  deploy/scripts/download_assets.sh
  deploy/tools/envs-validator/index.ts
  deploy/tools/envs-validator/schema.ts
  docs/ENVS.md
  icons/brands/graph.svg
  lib/hooks/useGraphLinks.tsx
  public/icons/name.d.ts
  ui/marketplace/MarketplaceAppCard.tsx
  ui/marketplace/MarketplaceAppCardLink.tsx
  ui/marketplace/MarketplaceAppGraphLinks.tsx
  ui/marketplace/MarketplaceAppModal.tsx
  ui/marketplace/MarketplaceList.tsx
  ui/marketplace/__screenshots__/MarketplaceAppModal.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/marketplace/__screenshots__/MarketplaceAppModal.pw.tsx_default_base-view-dark-mode-1.png
  ui/marketplace/__screenshots__/MarketplaceAppModal.pw.tsx_default_mobile-base-view-1.png
  ui/pages/Marketplace.tsx
  ui/pages/__screenshots__/Marketplace.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_dark-color-mode_with-banner-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_dark-color-mode_with-featured-app-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_base-view-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-base-view-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-with-banner-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-with-featured-app-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_with-banner-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_with-featured-app-dark-mode-1.png
Labels: enhancement, ENVs

#2312 `Unrecognized chain ID` error when adding network via mobile MetaMask
  lib/web3/useAddOrSwitchChain.tsx
Labels: bug

#2308 Homepage for rollups: Latest blocks vs. Latest batches
  configs/app/features/rollup.ts
  deploy/tools/envs-validator/schema.ts
  deploy/tools/envs-validator/test/.env.rollup
  docs/ENVS.md
  ui/pages/Home.tsx
Labels: ENVs

#2307 Contract call response displayed with empty values
  ui/address/contract/methods/form/ContractMethodResultPublicClient.pw.tsx
  ui/address/contract/methods/form/__screenshots__/ContractMethodResultPublicClient.pw.tsx_default_error-1.png
  ui/address/contract/methods/form/__screenshots__/ContractMethodResultPublicClient.pw.tsx_default_preview-mode-1.png
  ui/address/contract/methods/form/__screenshots__/ContractMethodResultPublicClient.pw.tsx_default_result-mode-1.png
  ui/address/contract/methods/form/resultPublicClient/ItemTuple.tsx
Labels: bug

#2290 Blocks list: add base fee
  docs/ENVS.md
  types/views/block.ts
  ui/blocks/BlocksListItem.tsx
  ui/blocks/BlocksTable.tsx
  ui/blocks/BlocksTableItem.tsx
  ui/blocks/utils.ts
  ui/pages/__screenshots__/Blocks.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/pages/__screenshots__/Blocks.pw.tsx_default_base-view-dark-mode-1.png
  ui/pages/__screenshots__/Blocks.pw.tsx_default_hidden-fields-1.png
  ui/pages/__screenshots__/Blocks.pw.tsx_default_mobile-base-view-1.png
  ui/pages/__screenshots__/Blocks.pw.tsx_default_mobile-hidden-fields-1.png
  ui/pages/__screenshots__/Blocks.pw.tsx_default_new-item-from-socket-1.png
  ui/pages/__screenshots__/Blocks.pw.tsx_default_socket-error-1.png
Labels: ENVs

#2326 Fix security vulnerability issues
  deploy/tools/affected-tests/yarn.lock
  deploy/tools/envs-validator/yarn.lock
  deploy/tools/feature-reporter/yarn.lock
  yarn.lock
Labels: dependencies

#2334 Add run-time variable to skip ENVs validation
  deploy/scripts/entrypoint.sh
Labels: tech, ENVs

#2325 Zapper integration
  configs/app/features/multichainButton.ts
  configs/envs/.env.base
  configs/envs/.env.eth
  configs/envs/.env.eth_sepolia
  configs/envs/.env.gnosis
  configs/envs/.env.main
  configs/envs/.env.optimism
  configs/envs/.env.zksync
  configs/envs/.env.zora
  deploy/tools/envs-validator/schema.ts
  deploy/tools/envs-validator/test/.env.base
  docs/ENVS.md
  types/client/multichainProviderConfig.ts
  ui/address/details/AddressMultichainButton.tsx
  ui/address/details/AddressNetWorth.pw.tsx
  ui/address/details/AddressNetWorth.tsx
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_dark-color-mode_with-multichain-button-internal-dark-mode-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_dark-color-mode_with-single-multichain-button-internal-dark-mode-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_base-view-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-external-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-internal-dark-mode-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-internal-small-screen-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-single-multichain-button-external-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-single-multichain-button-internal-dark-mode-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-two-multichain-button-external-1.png
Labels: enhancement, ENVs
