Repository blockscout/frontend, pull requests merged in 2024-06, with the labels that each got.

#1988 Fix lazy loading on NFT Inventory view
  ui/shared/nft/useNftMediaInfo.tsx
Labels: bug, performance

#2005 Add supported frontend versions column in ENVS.md
  docs/BUILD-TIME_ENVS.md
  docs/DEPRECATED_ENVS.md
  docs/ENVS.md
Labels: chore

#1989 fix multichain button for mobile
  ui/address/details/AddressNetWorth.pw.tsx
  ui/address/details/AddressNetWorth.tsx
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_dark-color-mode_with-multichain-button-internal-dark-mode-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-external-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-internal-dark-mode-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-internal-small-screen-1.png
Labels: bug

#1967 Add Ad banner to 404 page
  ui/shared/AppError/AppError.pw.tsx
  ui/shared/AppError/AppError.tsx
  ui/shared/AppError/__screenshots__/AppError.pw.tsx_default_block-lost-consensus-1.png
  ui/shared/AppError/__screenshots__/AppError.pw.tsx_default_status-code-404-1.png
  ui/shared/ad/AdBanner.tsx
  ui/shared/ad/AdBannerContent.tsx
Labels: enhancement

#1943 The possibility to query a contract with an empty array
  ui/address/contract/ABI/form/ContractMethodFieldInput.tsx
  ui/address/contract/ABI/form/ContractMethodFieldInputArray.tsx
  ui/address/contract/ABI/form/ContractMethodFieldInputTuple.tsx
  ui/address/contract/ABI/form/__screenshots__/ContractMethodForm.pw.tsx_dark-color-mode_base-view-mobile-dark-mode-1.png
  ui/address/contract/ABI/form/__screenshots__/ContractMethodForm.pw.tsx_default_base-view-mobile-dark-mode-1.png
  ui/address/contract/ABI/form/__screenshots__/ContractMethodForm.pw.tsx_mobile_base-view-mobile-dark-mode-1.png
  ui/address/contract/ABI/form/utils.test.ts
  ui/address/contract/ABI/form/utils.ts
Labels: bug

#2004 Resolve BENS names from URL directly to address page
  lib/address/useAddressMetadataInfoQuery.ts
  playwright/mocks/lib/growthbook/useFeatureValue.js
  ui/address/AddressAccountHistory.tsx
  ui/address/AddressBlocksValidated.tsx
  ui/address/AddressCoinBalance.tsx
  ui/address/AddressInternalTxs.tsx
  ui/address/AddressLogs.tsx
  ui/address/AddressTokenTransfers.tsx
  ui/address/AddressTokens.tsx
  ui/address/AddressTxs.tsx
  ui/address/AddressUserOps.tsx
  ui/address/AddressWithdrawals.tsx
  ui/address/utils/useAddressQuery.ts
  ui/address/utils/useCheckDomainNameParam.ts
  ui/pages/Address.tsx
  ui/shared/AppActionButton/useAppActionData.tsx
Labels: enhancement

#2009 Blueprint contracts support
  mocks/contract/info.ts
  types/api/contract.ts
  ui/address/contract/ContractCode.tsx
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_dark-color-mode_full-view-mobile-dark-mode-1.png
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_default_full-view-mobile-dark-mode-1.png
  ui/address/contract/__screenshots__/ContractCode.pw.tsx_mobile_full-view-mobile-dark-mode-1.png
Labels: enhancement

#2017 Wallet tooltip fixes
  ui/snippets/walletMenu/WalletTooltip.tsx
Labels: bug

#2034 Show a Zerion button only for EOA addresses
  mocks/address/address.ts
  ui/address/details/AddressNetWorth.pw.tsx
  ui/address/details/AddressNetWorth.tsx
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_dark-color-mode_with-multichain-button-internal-dark-mode-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_base-view-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-external-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-internal-dark-mode-1.png
  ui/address/details/__screenshots__/AddressNetWorth.pw.tsx_default_with-multichain-button-internal-small-screen-1.png
Labels: enhancement

#2039 Implement NFT instance metadata refetch button
  icons/refresh.svg
  lib/api/resources.ts
  lib/socket/types.ts
  lib/token/metadata/attributesParser.ts
  mocks/tokens/tokenInstance.ts
  package.json
  playwright/fixtures/socketServer.ts
  public/icons/name.d.ts
  stubs/token.ts
  types/api/token.ts
  ui/pages/TokenInstance.pw.tsx
  ui/pages/TokenInstance.tsx
  ui/pages/__screenshots__/TokenInstance.pw.tsx_default_metadata-update-1.png
  ui/pages/__screenshots__/TokenInstance.pw.tsx_default_metadata-update-2.png
  ui/pages/__screenshots__/TokenInstance.pw.tsx_default_metadata-update-3.png
  ui/pages/__screenshots__/TokenInstance.pw.tsx_default_metadata-update-failed-1.png
  ui/shared/AccountActionsMenu/AccountActionsMenu.tsx
  ui/shared/AccountActionsMenu/items/MetadataUpdateMenuItem.tsx
  ui/shared/AccountActionsMenu/items/PrivateTagMenuItem.tsx
  ui/shared/AccountActionsMenu/items/PublicTagMenuItem.tsx
  ui/shared/AccountActionsMenu/items/TokenInfoMenuItem.tsx
  ui/shared/AccountActionsMenu/parts/ButtonItem.tsx
  ui/shared/AccountActionsMenu/parts/MenuItem.tsx
  ui/shared/AccountActionsMenu/types.ts
  ui/shared/Page/PageTitle.tsx
  ui/tokenInstance/TokenInstanceDetails.pw.tsx
  ui/tokenInstance/TokenInstanceMetadata.tsx
  ui/tokenInstance/TokenInstanceMetadataFetcher.tsx
  ui/tokenInstance/TokenInstancePageTitle.tsx
  ui/tokenInstance/contexts/metadataUpdate.tsx
  ui/tokenInstance/details/TokenInstanceMetadataInfo.tsx
  yarn.lock
Labels: QA

#2031 Combine default and security score view on the Marketplace page
  types/client/marketplace.ts
  ui/marketplace/AppSecurityReport.tsx
  ui/marketplace/ContractListButton.tsx
  ui/marketplace/ContractListModal.tsx
  ui/marketplace/ContractSecurityReport.tsx
  ui/marketplace/MarketplaceAppCard.tsx
  ui/marketplace/MarketplaceAppIntegrationIcon.tsx
  ui/marketplace/MarketplaceAppModal.pw.tsx
  ui/marketplace/MarketplaceAppModal.tsx
  ui/marketplace/MarketplaceAppTopBar.tsx
  ui/marketplace/MarketplaceList.tsx
  ui/marketplace/MarketplaceListWithScores.tsx
  ui/marketplace/MarketplaceListWithScores/AppLink.tsx
  ui/marketplace/MarketplaceListWithScores/ListItem.tsx
  ui/marketplace/MarketplaceListWithScores/MoreInfoButton.tsx
  ui/marketplace/MarketplaceListWithScores/Table.tsx
  ui/marketplace/MarketplaceListWithScores/TableItem.tsx
  ui/marketplace/__screenshots__/MarketplaceAppModal.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/marketplace/__screenshots__/MarketplaceAppModal.pw.tsx_default_base-view-dark-mode-1.png
  ui/marketplace/__screenshots__/MarketplaceAppModal.pw.tsx_default_mobile-base-view-1.png
  ui/marketplace/useMarketplace.tsx
  ui/marketplace/useMarketplaceApps.tsx
  ui/marketplace/utils.ts
  ui/nameDomains/NameDomainsActionBar.tsx
  ui/nameDomains/utils.ts
  ui/pages/Marketplace.pw.tsx
  ui/pages/Marketplace.tsx
  ui/pages/Validators.tsx
  ui/pages/VerifiedContracts.tsx
  ui/pages/__screenshots__/Marketplace.pw.tsx_dark-color-mode_base-view-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_dark-color-mode_with-banner-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_dark-color-mode_with-featured-app-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_dark-color-mode_with-scores-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_base-view-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-base-view-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-with-banner-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-with-featured-app-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_mobile-with-scores-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_with-banner-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_with-featured-app-dark-mode-1.png
  ui/pages/__screenshots__/Marketplace.pw.tsx_default_with-scores-dark-mode-1.png
  ui/shared/solidityscanReport/SolidityscanReportButton.tsx
  ui/shared/sort/ButtonDesktop.tsx
  ui/shared/sort/ButtonMobile.tsx
  ui/shared/sort/Option.tsx
  ui/shared/sort/Sort.tsx
  ui/shared/sort/getSortValueFromQuery.ts
  ui/tokens/TokensActionBar.tsx
  ui/tokens/utils.ts
  ui/txs/TxsHeaderMobile.tsx
  ui/txs/useTxsSort.tsx
  ui/validators/utils.ts
  ui/verifiedContracts/utils.ts
Labels: enhancement

#2044 Mixpanel profiles
  lib/mixpanel/index.ts
  lib/mixpanel/useInit.tsx
  lib/mixpanel/userProfile.ts
  types/utils.ts
  ui/snippets/walletMenu/useWallet.tsx
Labels: enhancement
